#!/bin/bash
 
export COMPOSER_HOME="$OPENSHIFT_DATA_DIR/.composer"
 
if [ ! -f "$OPENSHIFT_DATA_DIR/composer.phar" ]; then
    curl -s https://getcomposer.org/installer | /usr/bin/php -- --install-dir=$OPENSHIFT_DATA_DIR
else
    /usr/bin/php $OPENSHIFT_DATA_DIR/composer.phar self-update
fi
 
unset GIT_DIR 
cd $OPENSHIFT_REPO_DIR/php 
/usr/bin/php $OPENSHIFT_DATA_DIR/composer.phar install

chmod -R 0777 $OPENSHIFT_REPO_DIR/php/app/cache
chmod -R 0777 $OPENSHIFT_REPO_DIR/php/app/logs
