puphpet.extension.elastic_search.homepage:
    pattern:  /
    defaults: { _controller: PuphpetExtensionElasticSearchBundle:Front:index }

puphpet.extension.elastic_search.manifest:
    pattern:  /manifest
    defaults: { _controller: PuphpetExtensionElasticSearchBundle:Manifest:index }
