parameters:

services:
    puphpet.extension.mailcatcher.configure:
        class: Puphpet\Extension\MailCatcherBundle\Configure
        arguments:
            - "@service_container"

    puphpet.extension.mailcatcher.front_controller:
        class: Puphpet\Extension\MailCatcherBundle\Controller\FrontController
        calls:
            - [ setContainer, [@service_container] ]

    puphpet.extension.mailcatcher.manifest_controller:
        class: Puphpet\Extension\MailCatcherBundle\Controller\ManifestController
        calls:
            - [ setContainer, [@service_container] ]
