parameters:

services:
    puphpet.extension.hhvm.configure:
        class: Puphpet\Extension\HhvmBundle\Configure
        arguments:
            - "@service_container"

    puphpet.extension.hhvm.front_controller:
        class: Puphpet\Extension\HhvmBundle\Controller\FrontController
        calls:
            - [ setContainer, [@service_container] ]

    puphpet.extension.hhvm.manifest_controller:
        class: Puphpet\Extension\HhvmBundle\Controller\ManifestController
        calls:
            - [ setContainer, [@service_container] ]
