puphpet.extension.vagrantfile.digital_ocean.homepage:
    pattern:  /
    defaults: { _controller: PuphpetExtensionVagrantfileDigitalOceanBundle:Front:index }

puphpet.extension.vagrantfile.digital_ocean.synced_folder:
    pattern: /synced-folder
    defaults: { _controller: PuphpetExtensionVagrantfileDigitalOceanBundle:Front:syncedFolder }

puphpet.extension.vagrantfile.digital_ocean.manifest:
    pattern:  /manifest
    defaults: { _controller: PuphpetExtensionVagrantfileDigitalOceanBundle:Manifest:index }
