puphpet.extension.xhprof.homepage:
    pattern:  /
    defaults: { _controller: PuphpetExtensionXhprofBundle:Front:index }

puphpet.extension.xhprof.manifest:
    pattern:  /manifest
    defaults: { _controller: PuphpetExtensionXhprofBundle:Manifest:index }
