empty_synced_folder:
    source: ~
    target: ~
    id: vagrant-root
    nfs: 'false'

available_providers:
    -
        name: virtualbox
        long_name: VirtualBox
        description: >
            <em>Windows, OSX and Linux</em>, <em>Performance: *</em><br />
            Free! Not as performant as VMWare. Free!
            <a href="https://www.virtualbox.org/wiki/Downloads" target="_blank">Download Virtualbox here</a>.
        default_ip: 192.168.56.101
    -
        name: vmware_fusion
        long_name: VMWare Fusion
        description: >
            <em>OSX-only</em>, <em>Performance: ***</em><br />
            More performant than VirtualBox.
            <a href="http://send.onenetworkdirect.net/z/33484/CD207605/" target="_blank">Requires purchase of VMWare Fusion</a>
            (affiliate link - help support this free service)
            and purchase of <a href="http://www.vagrantup.com/vmware" target="_blank">Vagrant VMWare Fusion Plugin</a>.
        default_ip: 192.168.57.101
    -
        name: vmware_workstation
        long_name: VMWare Workstation
        description: >
            <em>Linux and Windows</em>, <em>Performance: ***</em><br />
            More performant than VirtualBox.
            <a href="http://send.onenetworkdirect.net/z/33485/CD207605/" target="_blank">Requires purchase of VMWare Workstation</a>
            (affiliate link - help support this free service)
            and purchase of <a href="http://www.vagrantup.com/vmware" target="_blank">Vagrant VMWare Workstation Plugin</a>.
        default_ip: 192.168.57.101
    -
        name: parallels
        long_name: Parallels Desktop
        description: >
            <em>OSX-only</em>, <em>Performance: ***</em><br />
            More performant than VirtualBox.
            <a href="http://www.parallels.com/" target="_blank">Requires purchase of Parallels Desktop 9</a>
            and installing the <a href="https://github.com/Parallels/vagrant-parallels" target="_blank">Vagrant Parallels Plugin</a>.
        default_ip: 192.168.58.101

available_boxes:
    -
        url: puphpet/centos65-x64
        os: centos
        short_name: puphpet/centos65-x64
        long_name: CentOS 6.5 x64
        php_versions:
            - 5.5
            - 5.4
            - HHVM
    -
        url: puphpet/debian75-x64
        os: debian
        short_name: puphpet/debian75-x64
        long_name: Debian Wheezy 7.5 x64
        php_versions:
            - 5.5
            - 5.4
            - HHVM
    -
        url: puphpet/debian75-x32
        os: debian
        short_name: puphpet/debian75-x32
        long_name: Debian Wheezy 7.5 x32
        php_versions:
            - 5.5
            - 5.4
            - HHVM
    -
        url: puphpet/ubuntu1404-x64
        os: ubuntu
        short_name: puphpet/ubuntu1404-x64
        long_name: Ubuntu Trusty 14.04 LTS x64
        php_versions:
            - 5.5
            - HHVM
    -
        url: puphpet/ubuntu1204-x64
        os: ubuntu
        short_name: puphpet/ubuntu1204-x64
        long_name: Ubuntu Precise 12.04 LTS x64
        php_versions:
            - 5.5
            - 5.4
            - HHVM
