puphpet.extension.vagrantfile.local.homepage:
    pattern:  /
    defaults: { _controller: PuphpetExtensionVagrantfileLocalBundle:Front:index }

puphpet.extension.vagrantfile.local.synced_folder:
    pattern: /synced-folder
    defaults: { _controller: PuphpetExtensionVagrantfileLocalBundle:Front:syncedFolder }

puphpet.extension.vagrantfile.local.forwarded_port:
    pattern: /forwarded-port
    defaults: { _controller: PuphpetExtensionVagrantfileLocalBundle:Front:forwardedPort }

puphpet.extension.vagrantfile.local.manifest:
    pattern:  /manifest
    defaults: { _controller: PuphpetExtensionVagrantfileLocalBundle:Manifest:index }
