available_privileges:
    - ALL
    - CREATE
    - CONNECT
    - TEMPORARY

empty_database:
    name: ~
    user: ~
    password: ~
    grant: ALL
    sql_file: ~

available_versions:
    - "9.3"
    - "9.2"
    - "9.1"
    - "8.4"
